name = "OptimalPolicies"
uuid = "5e9a7149-b93e-4002-b93c-154786869f38"
authors = ["Yuqing Pan <yuqingpan@g.harvard.edu>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.6"
